# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{msg-qworker}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mathias Dalheimer"]
  s.date = %q{2011-07-26}
  s.default_executable = %q{qworker.rb}
  s.description = %q{This gem provides a queue worker infrastructure for a beanstalk queue. Jobs are defined within the framework.}
  s.email = %q{md@gonium.net}
  s.executables = ["qworker.rb", "producer.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "etc/flukso4rrc",
     "etc/qproducerrc",
     "etc/qworkerrc"
  ]
  s.homepage = %q{https://github.com/mysmartgrid/msg-qworker}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A reliable beanstalk queue processor in Ruby}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<uuid>, ["~> 2.3.2"])
      s.add_runtime_dependency(%q<beanstalk-client>, ["~> 1.1.0"])
    else
      s.add_dependency(%q<uuid>, ["~> 2.3.2"])
      s.add_dependency(%q<beanstalk-client>, ["~> 1.1.0"])
    end
  else
    s.add_dependency(%q<uuid>, ["~> 2.3.2"])
    s.add_dependency(%q<beanstalk-client>, ["~> 1.1.0"])
  end
end

